# -*- coding: utf-8 -*-
"""Chathila_Wijesinghe_Notebook1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChrE02W_UeaRgXFLc56192HfZjMJyclU

*   Notebook Author - Chathila Wijesinghe
"""

#Importing pandas library
import pandas as pd
#Importing plotly
import plotly.express as px
#Loading data into a DataFrame
df=pd.read_csv('/content/loan_approval_data.csv')

"""Python Lab - Seminar 1"""

# Display basic information about the dataset
print("\nDataset Info:")
print(df.info())

#Display first few rows
df.head()

"""Python Lab - Seminar 1"""

#Renaming variable
df.rename(columns={'emplyment_length': 'employment_length'}, inplace=True)

#Checking for trends, inconsistencies, columns with missing values, etc in numeric columns
df.describe()

"""Python Lab - Seminar 1"""

#Checking for trends, inconsistencies, columns with missing values, etc in categorical columns
df.describe(include='object')

"""Python Lab - Seminar 1"""

#Checking for missing values
print("\nMissing Values per variable:")
print(df.isnull().sum())

#Checking the percentage of missing data values per variable
#can be used to determine whether it's possible to remove the whole rows of missing values
print("\nMissing Value percentages per variable:")
print(df.isna().sum()/len(df)*100)

# Get total number of missing values
total_missing = df.isnull().sum().sum()
print(f"\nTotal number of missing values: {total_missing}")

# Get percentage of missing values
total_percent_missing = (total_missing / (df.shape[0] * df.shape[1])) * 100
print(f"Percentage of missing values: {total_percent_missing:.2f}%")

"""Python Lab - Seminar 1"""

#Display all 22 rows having a null variable
df[df.isnull().any(axis=1)]

"""Python Lab - Seminar 2"""

#Imputating 'payment_default_on_file' with the mode
print(f"No. of NULL values in 'payment_default_on_file': {df['payment_default_on_file'].isnull().sum()}")
print(f"Mode of 'payment_default_on_file': {df['payment_default_on_file'].mode()[0]}")

#As the mode covers 85% of the data & missing value percentage is 0.008%
df['payment_default_on_file'] = df['payment_default_on_file'].fillna(df['payment_default_on_file'].mode()[0])
print("\nImputated the NULL values of 'payment_default_on_file' with the Mode!")

#verifying
print(f"No. of NULL values remaining in 'payment_default_on_file': {df['payment_default_on_file'].isnull().sum()}")

"""Python Lab - Seminar 2"""

#Using box-plot to visually 'loan_interest_rate'
LIR_fig = px.box(df, x='loan_interest_rate')
LIR_fig.show()

"""Python Lab - Seminar 2"""

#Finding the median of 'loan_interest_rate'
print(f"No. of NULL values in 'loan_interest_rate': {df['loan_interest_rate'].isnull().sum()}")
median_rate = df['loan_interest_rate'].median()
print(f"Median of 'loan_interest_rate': {median_rate}")

#Replacing missing values of 'loan_interest_rate' with median
df['loan_interest_rate'] = df['loan_interest_rate'].fillna(median_rate)
print("\nImputated the NULL values of 'loan_interest_rate' with the Median!")

#verifying
print(f"No. of NULL values remainging in 'loan_interest_rate': {df['loan_interest_rate'].isnull().sum()}")

"""Python Lab - Seminar 1"""

#Removing negative values in loan_interest_rate
IR_neg_values = (df['loan_interest_rate'] < 0).sum()
print(f"No. of negative values in 'loan_interest_rate': {IR_neg_values}")

if IR_neg_values < 5:
    df = df[df['loan_interest_rate'] >= 0]
    print("\nRemoved the negative values in 'loan_interest_rate'!")
    print(f"No. of negative values remaining: {(df['loan_interest_rate'] < 0).sum()}")
else:
    print("\nToo many negative vlaues, use imputation")

"""Python Lab - Seminar 2"""

# Construct the histogram plot for the age histogarm
#To get a visual representation of the skewness inorder to determin wether to use mean, median, mode.
Age_his = px.histogram(df, x='age', nbins=40)

#Using box-plot to visually 'age'
Age_box = px.box(df, x='age')

#plot all constructed graphs
Age_his.show()
Age_box.show()

"""Python Lab - Seminar 2"""

#Finding the median of 'age'
print(f"No. of NULL values in 'age': {df['age'].isnull().sum()}")
median_age = df['age'].median()
print(f"Median of 'age': {median_age}")

#Replacing missing values of 'age' with median
df['age'] = df['age'].fillna(median_age)
print("\nImputated the NULL values of 'age' with the Median!")

#verifying
print(f"No. of NULL values remainging in 'age': {df['age'].isnull().sum()}")

#Removing outliers in 'age'
abv_90 = (df['age'] > 90).sum()
print(f"No. of age's above 90: {abv_90}")

if abv_90 < 5:
    df = df[df['age'] <= 90]
    print("\nRemoved all age's above 90!")
    print(f"No. of age's above 90 remaining: {(df['age'] > 90).sum()}")
else:
    print("\nToo many data errors, use imputation")

#Verifying all null values are removed
# Get total number of missing values
total_missing = df.isnull().sum().sum()
print(f"Total number of missing values: {total_missing}")

# Get percentage of missing values
total_percent_missing = (total_missing / (df.shape[0] * df.shape[1])) * 100
print(f"Percentage of missing values: {total_percent_missing:.2f}%")

"""Python Lab - Seminar 2"""

#Using box-plot to visually check for any outliers in 'income'
Income_box = px.box(df, x='income')
Income_box.show()

"""Python Lab - Seminar 2"""

# Calculate IQR for income
Q1 = df['income'].quantile(0.25)
Q3 = df['income'].quantile(0.75)
IQR = Q3 - Q1

# Define upper bound of 'income'
upper_bound = Q3 + 1.5 * IQR

print(f"Q1 of 'income': {Q1}")
print(f"Q3 of 'income': {Q3}")
print(f"IQR of 'income': {IQR}")
print(f"'income' Upper bound: {upper_bound}")

# Define age threshold (young group)
age_threshold = df['age'].quantile(0.25)

print(f"'age' threshold (young group): {age_threshold}")

# Find inconsitent income values
mask = (df['income'] > upper_bound) & (df['age'] < age_threshold)

# Show suspicious rows
print(f"\nNo. of extreme 'income' rows: {mask.sum()}")

# Remove the inconsistent values
df = df[~mask]

print("\nRemoved all unrealistic high-income young-age outliers!")

# Verifying
remaining = ((df['income'] > upper_bound) & (df['age'] < age_threshold)).sum()
print(f"No. of extreme 'income' rows remaining: {remaining}")

"""Python Lab - Seminar 2"""

#Using box-plot to visually check for any outliers in 'employment_length'
Emp_box = px.box(df, x='employment_length')
Emp_box.show()

#Removing 'employment_length' greater than 70
above_70 = (df['employment_length'] > 70).sum()
print(f"No. of rows where 'employment_length' greater than 70: {above_70}")
#Removing those rows
df = df[(df['employment_length'] < 70)]
print("\nRemoved all 'Employment_length' above 70!")
print(f"No. of 'employment_length' > 70 rows remaining: {(df['employment_length'] > 70).sum()}")

#checking for employement length greater than (age-15)
above_age = (df['employment_length'] > (df['age'] - 15)).sum()
print(f"\n\nNo. of rows where 'employment_length' > (age-15): {above_age}")
#Removing those rows
df = df[~(df['employment_length'] > (df['age'] - 15))]
print("\nRemoved 'employment_length' > (age-15) data errors!")
#verifying that the data is removed
print(f"No. of 'employment_length' > (age-15) remaining: {(df['employment_length'] > (df['age'] - 15)).sum()}")

"""Python Lab - Seminar 2"""

#Using box-plot to visually check for any outliers in 'loan_amount'
Loan_box = px.box(df, x='loan_amount')
Loan_box.show()

"""Python Lab - Seminar 2"""

#Using box-plot to visually check for any outliers in 'loan_income_ratio'
LI_Ratio_box = px.box(df, x='loan_income_ratio')
LI_Ratio_box.show()

# Checking loan_interest_ratio errors
# Calculating actual loan-interest ratio
calc_ratio_001 = ((df['loan_amount'] / df['income'])).round(3)

# Finding values greater/lesser than the actual value, where 'actual value' less than 0.01
below_001 = (
    (calc_ratio_001 < 0.01) &
    (
        (calc_ratio_001 > df['loan_income_ratio'] + 0.003) |
        (calc_ratio_001 < df['loan_income_ratio'] - 0.003)
    )
).sum()

print(f"No. of incorrect below 0.01 loan_income_ratio values: {below_001}")

# Condidtion for replacing the incorrect values
condition = (
    (calc_ratio_001 < 0.01) &
    (
        (calc_ratio_001 > df['loan_income_ratio'] + 0.003) |
        (calc_ratio_001 < df['loan_income_ratio'] - 0.003)
    )
)

# Replacing the below 0.01 incorrect values
df.loc[condition, 'loan_income_ratio'] = calc_ratio_001[condition]
print(f"\nReplaced the incorrect {below_001} values with the correct values!")

# verifying
below_001 = (
    (calc_ratio_001 < 0.01) &
    (
        (calc_ratio_001 > df['loan_income_ratio'] + 0.003) |
        (calc_ratio_001 < df['loan_income_ratio'] - 0.003)
    )
).sum()
print(f"No. of below 0.01 loan_income_ratio errors remaining: {below_001}")

calc_ratio = calc_ratio_001.round(2)

# Finding values greater/lesser than the actual value, where 'actual value' less than 0.1
below_01 = (
    (calc_ratio < 0.1) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.03) |
        (calc_ratio < df['loan_income_ratio'] - 0.03)
    )
).sum()

print(f"\n\nNo. of incorrect below 0.1 loan_income_ratio values: {below_01}")

# Condidtion for replacing the incorrect values
condition = (
    (calc_ratio < 0.1) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.03) |
        (calc_ratio < df['loan_income_ratio'] - 0.03)
    )
)

# Replacing the incorrect below 0.1 values
df.loc[condition, 'loan_income_ratio'] = calc_ratio[condition]
print(f"\nReplaced the incorrect {below_01} values with the correct values!")

# Verifying
below_01 = (
    (calc_ratio < 0.1) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.03) |
        (calc_ratio < df['loan_income_ratio'] - 0.03)
    )
).sum()
print(f"No. of below 0.1 loan_income_ratio errors remaining: {below_01}")

# Finding values greater/lesser than the actual value, where 'actual value' less than 1.0
below_1 = (
    (calc_ratio < 1.0) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.03) |
        (calc_ratio < df['loan_income_ratio'] - 0.03)
    )
).sum()

print(f"No. of incorrect below 1.0 loan_income_ratio values: {below_1}")

# Condidtion for replacing the incorrect values
condition = (
    (calc_ratio < 1.0) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.03) |
        (calc_ratio < df['loan_income_ratio'] - 0.03)
    )
)

# Replacing the incorrect below 1.0 values
df.loc[condition, 'loan_income_ratio'] = calc_ratio[condition]
print(f"\nReplaced the incorrect {below_1} values with the correct values!")

#verifying
below_1 = (
    (calc_ratio < 1.0) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.03) |
        (calc_ratio < df['loan_income_ratio'] - 0.03)
    )
).sum()
print(f"No. of below 1.0 loan_income_ratio errors remaining: {below_1}")



# Finding values greater/lesser than the actual value, where 'actual value' greater than 1.0
above_1 = (
    (calc_ratio > 1.0) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.3) |
        (calc_ratio < df['loan_income_ratio'] - 0.3)
    )
).sum()

print(f"\n\nNo. of incorrect above 1.0 loan_income_ratio values: {above_1}")

# Condidtion for replacing the incorrect values
condition = (
    (calc_ratio > 1.0) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.3) |
        (calc_ratio < df['loan_income_ratio'] - 0.3)
    )
)

# Replacing the incorrect below 0.1 values
df.loc[condition, 'loan_income_ratio'] = calc_ratio[condition]
print(f"\nReplaced the incorrect {above_1} values with the correct values!")

# Verifying
above_1 = (
    (calc_ratio > 1.0) &
    (
        (calc_ratio > df['loan_income_ratio'] + 0.3) |
        (calc_ratio < df['loan_income_ratio'] - 0.3)
    )
).sum()
print(f"No. of above 1.0 loan_income_ratio errors remaining: {above_1}")

"""Python Lab - Seminar 2"""

#Using box-plot to visually check for any outliers in 'credit_history_length'
CH_length_box = px.box(df, x='credit_history_length')
CH_length_box.show()

#checking for credit_history_length greater than (age-18)
credit_above_age = (df['credit_history_length'] > (df['age'] - 17)).sum()
print(f"No. of rows where credit_history_length > (age-17): {credit_above_age}")

#removing the error values
df = df[~(df['credit_history_length'] > (df['age'] - 17))]
print(f"\n{credit_above_age} credit_history_length data errors removed!")

#verifying
print(f"credit_history_length data errors remaining: {(df['credit_history_length'] > (df['age'] - 17)).sum()}")

"""Python Lab - Seminar 2"""

#Using box-plot to visually check for any outliers in 'max_allowed_loan'
Max_loan = px.box(df, x='max_allowed_loan')
Max_loan.show()

#Checking for negative 'max allowed loan' values
invalid_max_loans = (df['max_allowed_loan'] < 0 ).sum()
print("Invalid_max_loans :- 'max_allowed_loan' < 0")
print(f"No. of Invalid_max_loans: {invalid_max_loans}")

#Removing Invalid loans
df = df[~(df['max_allowed_loan'] < 0)]
print(f"\nAll {invalid_max_loans} invalid max_allowed_loan's removed!")

#verifying
print(f"No. of Invalid_max_loans remaining: {(df['max_allowed_loan'] < 0 ).sum()}")

# Total no. of rows removed
final_rows = df['income'].count()
removed_rows = 58645 - final_rows
removed_pct = ((removed_rows / 58645) * 100).round(2)
print(f"\nNo. of rows removed: {removed_rows}")
print(f"Percentage of rows removed: {removed_pct}%")

#Cleaned dataset
print(f"\ncleaned dataset: ")
df.describe(include="all")

"""Python Lab - Seminar 1 & 2"""

# chaging object types to numeric
df['payment_default_on_file'] = df['payment_default_on_file'].map({'Y': 0, 'N': 1})

#Dropping unwanted columns
df.drop(['id', 'loan_intent', 'payment_default_on_file'], axis=1, inplace=True)

df['home_ownership'] = pd.Categorical(
    df['home_ownership'],
    categories=['OTHER', 'MORTGAGE', 'OWN', 'RENT'],  # put OTHER first
    ordered=False
)

df = pd.get_dummies(df, columns=['home_ownership'], drop_first=True)

# Convert only the dummy columns to 0/1
dummy_cols = [col for col in df.columns if col.startswith('home_ownership_')]
df[dummy_cols] = df[dummy_cols].astype(int)

#Saving Dataset for classification model
df.drop(columns=['max_allowed_loan']).to_csv(r'/content/classification_loan_data.csv', index=False)
print("\nClassification dataset saved as: classification_loan_data.csv")

# Filter only approved loans (0)
df = df[df['loan_approval_status'] == 0]

#Saving Dataset for Regression model
df.drop(columns=['loan_approval_status']).to_csv(r'/content/regression_loan_data.csv', index=False)
print("\nRegression dataset saved as: regression_loan_data.csv")

"""Python Lab - Seminar 1 & 2"""

#Loading classifiaction data into a DataFrame
classification_df=pd.read_csv('/content/classification_loan_data.csv')

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

#Retained variable information
print("classification dataset retained variable descriptions :\n")
print(classification_df.describe(include='all'))
print("\n\nclassification dataset retained variable scale types :\n")
print(classification_df.dtypes)

"""Python Lab - Seminar 1 & 2"""

#Destribution of taget varibale of calssification dataset
counts = classification_df['loan_approval_status'].value_counts().reset_index()
counts.columns = ['loan_approval_status', 'count']

counts['loan_approval_status'] = counts['loan_approval_status'].map({0: 'Yes', 1: 'No'})

target_var = px.bar(counts,
              x='loan_approval_status',
              y='count',
              title="Distribution of Target Variable")

target_var.show()

"""Python Lab - Seminar 1"""

# Loading regression data into a DataFrame
regression_df=pd.read_csv('/content/regression_loan_data.csv')

# Retained variable information
print(f"Regression dataset dimensions: {regression_df.shape}")

# Reatained features
features = regression_df.columns
print("\n\nList of retained features' names in regression dataset:\n")
list(features)